import Color from "./Color";
import { RFValue } from "react-native-responsive-fontsize";

export default {
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  gradientBackground: {
    paddingBottom: 10,
    marginBottom: 0,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: RFValue(18),
    alignItems: "center",
    marginTop: RFValue(8),
  },
  addressContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationIcon: {
    tintColor: Color.GREY_COLOR,
    height: RFValue(20),
    width: RFValue(20),
  },
  addressText: {
    color: Color.BLACK_COLOR,
    fontWeight: "500",
    marginStart: RFValue(8),
  },
  userIcon: {
    height: RFValue(38),
    width: RFValue(38),
  },
  searchFilterContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: RFValue(18),
    alignItems: "center",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    paddingHorizontal: RFValue(8),
    borderRadius: RFValue(10),
    elevation: 1,
    borderWidth: 0.5,
    borderColor: "#B6B5B5",
    width: "85%",
  },
  searchIcon: {
    tintColor: Color.GREY_COLOR,
    height: RFValue(18),
    width: RFValue(18),
  },
  searchInput: {
    borderColor: Color.GREY_COLOR,
    backgroundColor: Color.WHITE_COLLOR,
    height: RFValue(40),
    borderRadius: RFValue(10),
    fontSize: RFValue(15),
    flex: 1,
  },
  micIcon: {
    height: RFValue(20),
    width: RFValue(20),
  },
  filterContainer: {
    width: "12%",
    backgroundColor: "white",
    borderRadius: RFValue(10),
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    elevation: 3,
  },
  filterIcon: {
    height: RFValue(30),
    width: RFValue(30),
  },
  View2: {
    backgroundColor: Color.WHITE_COLLOR,
    flex: 1,
    borderTopLeftRadius: RFValue(10),
    borderTopRightRadius: RFValue(10),
    position: "relative",
    marginTop: -20,
    paddingVertical: RFValue(10),
  },

  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    // marginHorizontal: RFValue(20),
    // marginTop: RFValue(10),
    // padding: RFValue(5),
    paddingHorizontal: RFValue(8),
    borderRadius: RFValue(10),
    elevation: 1,
    borderWidth: 0.5,
    borderColor: "#B6B5B5",
    width: "85%",
  },

  searchInput: {
    borderColor: Color.GREY_COLOR,
    backgroundColor: Color.WHITE_COLLOR,
    height: RFValue(40),
    borderRadius: RFValue(10),
    fontSize: RFValue(15),
  },

  like_txt: {
    color: Color.GREY_COLOR,
    fontSize: RFValue(15),
    textAlign: "center",
    marginVertical: RFValue(10),
    fontWeight: "500",
  },
  itemContainer: {
    marginRight: RFValue(10),
    borderRadius: RFValue(10),
    overflow: "hidden",
  },
  gradient: {
    borderRadius: RFValue(10),
    alignItems: "center",
    width: RFValue(80),
    height: RFValue(60),
  },
  itemImage: {
    height: RFValue(40),
    width: RFValue(40),
    top: 4,
  },
  itemText: {
    color: Color.BLACK_COLOR,
    fontSize: RFValue(10),
    textAlign: "center",
    fontWeight: "500",
  },
  all_res: {
    color: Color.BLACK_COLOR,
    fontSize: RFValue(15),
    marginStart: RFValue(10),
    marginTop: RFValue(10),
    fontWeight: "500",
  },
  listContainer: {
    paddingHorizontal: RFValue(10),
  },
  sortitemContainer: {
    marginRight: RFValue(10),
    borderRadius: RFValue(8),
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: Color.GREY_COLOR,
    backgroundColor: Color.WHITE_COLLOR,
    height: RFValue(22),
    paddingHorizontal: RFValue(10),
    elevation: 3,
  },
  sortitemText: {
    fontSize: RFValue(12),
    color: Color.GREY_COLOR,
  },
  sortIcon: {
    width: RFValue(15),
    height: RFValue(15),
    marginLeft: RFValue(5),
  },
  listContainer: {
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(10),
    backgroundColor: Color.WHITE_COLLOR,
  },
  productCard: {
    backgroundColor: Color.WHITE_COLLOR,
    marginBottom: RFValue(15),
    borderRadius: RFValue(10),
    paddingHorizontal: 0,
    paddingVertical: 0,
    elevation: 2,
  },
  dottedDivider: {
    borderStyle: "dashed",
    borderWidth: 2,
    borderColor: Color.LIGHT_BLUE_COLOR,
    marginHorizontal: 0,
    marginTop: RFValue(10),
  },
  offerDeliveryContainer: {
    backgroundColor: Color.LIGHT_BLUE_COLOR,
    padding: RFValue(5),
    borderBottomLeftRadius: RFValue(10),
    borderBottomRightRadius: RFValue(10),
  },
  offerText: {
    color: Color.BLUE_COLOR,
    fontSize: RFValue(13),
    fontWeight: "500",
    textAlign: "center",
  },
  productImage: {
    height: RFValue(120),
    width: "100%",
    justifyContent: "space-between",
    borderTopLeftRadius: RFValue(10),
    borderTopRightRadius: RFValue(10),
    overflow: "hidden",
  },
  quantityText: {
    color: Color.WHITE_COLLOR,
    fontSize: RFValue(12),
    position: "absolute",
    top: RFValue(10),
    left: RFValue(10),
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: RFValue(5),
    borderRadius: RFValue(5),
  },
  ratingContainer: {
    position: "absolute",
    top: RFValue(10),
    right: RFValue(10),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: RFValue(5),
    borderRadius: RFValue(5),
  },
  ratingText: {
    color: Color.WHITE_COLLOR,
    fontSize: RFValue(12),
    marginRight: RFValue(4),
  },
  starIcon: {
    height: RFValue(14),
    width: RFValue(14),
    tintColor: "#FFD700",
  },
  titleText: {
    fontSize: RFValue(16),
    fontWeight: "bold",
    color: Color.BLACK_COLOR,
    // marginTop: RFValue(8),
  },
  subTagList: {
    // marginTop: RFValue(5),
  },
  subTagText: {
    backgroundColor: Color.GREY_COLOR,
    color: Color.WHITE_COLLOR,
    fontSize: RFValue(10),
    paddingHorizontal: RFValue(8),
    paddingVertical: RFValue(3),
    borderRadius: RFValue(15),
    marginRight: RFValue(5),
  },
  timeDurationContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: RFValue(10),
    marginHorizontal: RFValue(10),
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  clockIcon: {
    height: RFValue(14),
    width: RFValue(14),
    marginRight: RFValue(5),
  },
  timeText: {
    color: Color.GREY_COLOR,
    fontSize: RFValue(12),
  },
  durationText: {
    color: Color.GREY_COLOR,
    fontSize: RFValue(12),
  },
  offerText: {
    color: Color.BLUE_COLOR,
    fontSize: RFValue(13),
    marginBottom: RFValue(5),
    fontWeight: "500",
    textAlign: "center",
  },
  deliveryText: {
    color: Color.BLACK_COLOR,
    fontSize: RFValue(12),
  },
  nameView: { flexDirection: "row", alignItems: "center" },
  place_iocn: {
    tintColor: Color.GREY_COLOR,
    height: RFValue(15),
    width: RFValue(15),
  },
  bikeContainer: {
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    bottom: RFValue(8),
    left: RFValue(10),
  },
  bikeIcon: {
    width: RFValue(20),
    height: RFValue(20),
    marginRight: RFValue(5),
  },
  deliveryText: {
    fontSize: RFValue(13),
    color: "#fff",
    fontWeight: "500",
  },
  ProlistContainer: {
    paddingHorizontal: RFValue(10),
  },
  imge_grad: {
    position: "absolute",
    bottom: RFValue(0),
    height: 30,
    width: "100%",
  },
  free_del_view: { height: 30, width: "100%" },
  mic_div:{
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "flex-end",
    flex: 1,
  },
  mic_dv:{
    height: 30,
    backgroundColor: Color.GREY_COLOR,
    width: 1,
  },
};
